const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_CURRENT_USER_NULL: "SET_CURRENT_USER_NULL",
  SET_USERS: "SET_USERS",
  SET_FAVORITE_SPACE: "SET_FAVORITE_SPACE",
};

export default UserActionTypes;
